name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Name of the Docker image'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f ./bot/Dockerfile ./bot --tag ${{ github.event.inputs.imagename }}:$(date +%s)
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: donlandevsummit.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

